<?

$emoticons = array(
':angel:'    => "icon_angel.gif",
':applause:' => "icon_applause.gif",
':ass:'      => "icon_ass.gif",
':bemad:'    => "icon_bemad.gif",
':biggrin:'  => "icon_biggrin.gif",
':boogie:'   => "icon_boogie.gif",
':cheer:'    => "icon_cheer.gif",
':confused:' => "icon_confused.gif",
':cool:'     => "icon_cool.gif",
':cry:'      => "icon_cry.gif",
':cry2:'     => "icon_cry2.gif",
':dead:'     => "icon_dead.gif",
':eek:'      => "icon_eek.gif",
':embarace:' => "icon_embarace.gif",
':evil:'     => "icon_evil.gif",
':exclaim:'  => "icon_exclaim.gif",
':ill:'      => "icon_ill.gif",
':kiss:'     => "icon_kiss.gif",
':laugh:'    => "icon_laugh.gif",
':lol:'      => "icon_lol.gif",
':mad:'      => "icon_mad.gif",
':mute:'     => "icon_mute.gif",
':nono:'     => "icon_nono.gif",
':please:'   => "icon_please.gif",
':puke:'     => "icon_puke.gif",
':question:' => "icon_question.gif",
':razz:'     => "icon_razz.gif",
':redface:'  => "icon_redface.gif",
':rolleyes:' => "icon_rolleyes.gif",
':ronf:'     => "icon_ronf.gif",
':sad:'      => "icon_sad.gif",
':sarcastic' => "icon_sarcastic.gif",
':sigh:'     => "icon_sigh.gif",
':smile:'    => "icon_smile.gif",
':smooch:'   => "icon_smooch.gif",
':surprised' => "icon_surprised.gif",
':suspect:'  => "icon_suspect.gif",
':umbrella:' => "icon_umbrella.gif",
':verysad:'  => "icon_verysad.gif",
':whistle:'  => "icon_whistle.gif",
':wink:'     => "icon_wink.gif",
);

?>
